applications:
  stock-java-service:
    message: Configured by Azure Spring Cloud - stock-java-service
  price-java-service:
    message: Configured by Azure Spring Cloud - price-java-service
  security-java-service:
    message: Configured by Azure Spring Cloud - security-java-service
  stock-dotnet-service:
    message: Configured by Azure Spring Cloud - stock-dotnet-service
  price-dotnet-service:
    message: Configured by Azure Spring Cloud - price-dotnet-service
  security-dotnet-service:
    message: Configured by Azure Spring Cloud - security-dotnet-service
    azure:
      cosmosdb:
        uri: https://cosmosdb-azure-spring-cloud.documents.azure.com:443/
        key: PxI5mEpcTy87i1kZZOHEfdv7P1C8MHHYoV4mDH4g6MMeGbomBDYKgtb5hCFhNpyJe9iuFRrhGgm6G0j3xENtPQ==
        database: TradingEAC-Security